### ISSUE TITLE
Error executing 'static:app.load'

### ISSUE THREAD

**Issue by Janus-SGN** [julianlam/nodebb-plugin-2factor#1]
Hello,

I got this error :

```
[plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-2factor'
Error: Route.get() requires callback functions but got a [object Undefined]
    at Route.(anonymous function) [as get] (/var/www/nodebb/node_modules/express/lib/router/route.js:196:15)
    at Function.proto.(anonymous function) [as get] (/var/www/nodebb/node_modules/express/lib/router/index.js:510:19)
    at Object.helpers.setupPageRoute (/var/www/nodebb/src/routes/helpers.js:8:9)
    at Object.plugin.init [as method] (/var/www/nodebb/node_modules/nodebb-plugin-2factor/library.js:25:14)
    at /var/www/nodebb/src/plugins/hooks.js:133:14
    at /var/www/nodebb/node_modules/async/lib/async.js:122:13
    at _each (/var/www/nodebb/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/var/www/nodebb/node_modules/async/lib/async.js:121:9)
    at fireStaticHook (/var/www/nodebb/src/plugins/hooks.js:122:9)
    at Object.Plugins.fireHook (/var/www/nodebb/src/plugins/hooks.js:68:5)
```

My system informations : 
```
Nodejs : 0.10.40
NPM : 1.4.28
OS : Debian
NodeBB : 0.7.1
```

I saw in the sources that the plugin is compatible with version 0.7.2.
Can you try to fix it for version 0.7.1 please ?

**Comment by julianlam** [comment]
Unfortunately not, but 0.7.2 launches today, so that might work for you :sMile:

**Comment by Janus-SGN** [comment]
Ok, thank you ;)

**Comment by julianlam** [comment]
The code in 0.7.2 that this plugin requires is now committed and pushed to the master branch, if you wish to use that branch instead.
