### ISSUE TITLE
tries using connect-ensure-login from core

### ISSUE THREAD

**Issue by barisusakli** [julianlam/nodebb-plugin-2factor#55]
021-03-14T02:51:52.591Z [4570/8085] - error: Error: Cannot find module 'connect-ensure-login'
Require stack:
- /home/nodebb/community.nodebb.org/require-main.js
- /home/nodebb/community.nodebb.org/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.require.main.require (/home/nodebb/community.nodebb.org/require-main.js:8:10)
    at Object.<anonymous> (/home/nodebb/community.nodebb.org/node_modules/nodebb-plugin-2factor/library.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-2factor/commit/040b44665f9e2500ed007161212159cf9b2569aa
